trials: 5
results_dir: results/xor/

shared_params:
  # Dataset Configuration
  dataset_config:
    dataset: xor
    dataset_size: 3000
    batch_size: 256
    num_workers: 8
    root_dir: data/
    sampling_percent: 1
    test_subsampling: 1

  # Intervention evaluation
  intervention_config:
    competence_levels: [1, 0]
    intervention_freq: 1
    intervention_batch_size: 1024
    intervention_policies:
      - policy: "random"
        group_level: True
        use_prior: False
  # Representation metrics
  # Change to False if you want representation metrics to be included in the
  # evaluation (may significantly increase experiment times)
  skip_repr_evaluation: True

  top_k_accuracy: null
  save_model: True
  patience: 15
  emb_size: 128
  extra_dims: 0
  concept_loss_weight: 1
  learning_rate: 0.01
  scheduler_step: 20
  weight_decay: 0
  weight_loss: False
  c_extractor_arch: synth_extractor
  max_epochs: 500
  optimizer: adam
  bool: False
  early_stopping_monitor: val_loss
  early_stopping_mode: min
  early_stopping_delta: 0.0
  check_val_every_n_epoch: 30
  linear_c2y: True
  momentum: 0.9
  sigmoidal_prob: False

runs:
    - architecture: 'ConceptEmbeddingModel'
      run_name: "CEM"
      sigmoidal_prob: True
      training_intervention_prob: 0.25
      embedding_activation: "leakyrelu"

    - architecture: 'ConceptBottleneckModel'
      run_name: "CBM_Bool"
      bool: True
      extra_dims: 0
      sigmoidal_prob: True

    - architecture: 'ConceptBottleneckModel'
      run_name: "CBM_Sigmoid"
      bool: False
      extra_dims: 0
      sigmoidal_prob: True

    - architecture: 'ConceptBottleneckModel'
      run_name: "CBM_Logit"
      embedding_activation: "leakyrelu"
      bool: False
      extra_dims: 0
      sigmoidal_prob: False

    - architecture: 'ConceptBottleneckModel'
      run_name: "CBM_Hybrid_Sigmoid"
      bool: False
      extra_dims: "{{({emb_size} - 1) * {n_concepts}}}"
      bottleneck_nonlinear: "leakyrelu"
      sigmoidal_extra_capacity: False
      sigmoidal_prob: True

    - architecture: 'ConceptBottleneckModel'
      run_name: "CBM_Hybrid_Logit"
      bool: False
      extra_dims: "{{({emb_size} - 1) * {n_concepts}}}"
      bottleneck_nonlinear: "leakyrelu"
      sigmoidal_extra_capacity: False
      sigmoidal_prob: False

    - architecture: 'SequentialConceptBottleneckModel'
      run_name: "CBM_Seq"
      embedding_activation: "leakyrelu"
      bool: False
      extra_dims: 0
      sigmoidal_extra_capacity: False
      sigmoidal_prob: True

    - architecture: 'IndependentConceptBottleneckModel'
      run_name: "CBM_Ind"
      embedding_activation: "leakyrelu"
      bool: False
      extra_dims: 0
      sigmoidal_extra_capacity: False
      sigmoidal_prob: True

    - architecture: 'ConceptBottleneckModel'
      run_name: "DNN"
      bool: False
      extra_dims:  "{{({emb_size} - 1) * {n_concepts}}}"
      bottleneck_nonlinear: "leakyrelu"
      sigmoidal_extra_capacity: False
      sigmoidal_prob: True
      concept_loss_weight: 0